apiVersion: v1
kind: Service
metadata:
  name: prueba-api-service
spec:
  type: NodePort
  selector:
    app: prueba-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007